### ISSUE TITLE
Migrate Terraform setup from tink PR

### ISSUE THREAD

**Issue by gianarb** [tinkerbell/sandbox#1]
When those two PRs will be merged we should migrate the Terraform code here and *delete it from [tinkerbell/tink](https://github.com/tinkerbell/tink)

https://github.com/tinkerbell/tinkerbell.org/pull/129
https://github.com/tinkerbell/tink/pull/276

`* I would like to delete it, not sure what other people think about that`

**Comment by gauravgahlot** [comment]
IMHO it makes complete sense to have all the setup bits (for users) under sandbox.

**Comment by gianarb** [comment]
Done
