### ISSUE TITLE
Should we drop virtualbox in favor of vagrant + libvirt as the virtualization option?

### ISSUE THREAD

**Issue by mmlb** [tinkerbell/sandbox#113]
Recent virtualbox on macos breaks with the sandbox setup we currently have (#112 ).
Also, apparently its not guaranteed that virtualbox will ever be ported to arm64 macs.
It looks like libvirt works on macos<sup>[1]</sup> and there are patches floating around for libvirt + macos + arm<sup>[2]</sup> which I hope would land in upstream (if it hasn't). So is virtualbox on the chopping block?

[1]: https://www.arthurkoziel.com/running-virt-manager-and-libvirt-on-macos/
[2]: https://stackoverflow.com/questions/66833240/libvirt-on-apple-silicon-with-qemu-system-aarch64

**Comment by micahhausler** [comment]
Can we still support bare metal/Docker Compose?

**Comment by mmlb** [comment]
Oops this is very poorly worded, I'll update both the title and body. My intent was to drop virtualbox and only support vagrant + libvirt as the sole virtualization option (leaving baremetal alone).

**Comment by jacobweinstock** [comment]
I am in favor of not dropping vagrant+virtualbox. I use it all the time. one option is to make the VirtualBox dependency version explicit. We can support the current working version(s) and then when newer versions stabilize we update.

**Comment by mmlb** [comment]
@jacobweinstock Have you updated to latest mac os? Or do you use it on linux too?

**Comment by jacobweinstock** [comment]
Yes and no. I have 2 Apple machines. One is using Monterey and one Big Sur. I don't use the Linux sandbox as often. When I do though, I use the Docker Compose or Vagrant and Libvirt.

**Comment by jacobweinstock** [comment]
There are trade-offs to using libvirt on Mac OS over VirtualBox. A significant one, for me, is that I believe libvirt on Mac OS requires homebrew (at least according to the [link](https://www.arthurkoziel.com/running-virt-manager-and-libvirt-on-macos/) posted in the initial issue). I don't run homebrew. That would be a required dependency. So we are trading dependencies from Virtualbox to homebrew+libvirt.

**Comment by mmlb** [comment]
Thanks for the extra context. I'm not seeing where libvirt *requires* homebrew. What package manager do you use on mac?

**Comment by jacobweinstock** [comment]
> Thanks for the extra context. I'm not seeing where libvirt _requires_ homebrew. 

This [link](https://www.arthurkoziel.com/running-virt-manager-and-libvirt-on-macos/) shows the libvirt installation requiring homebrew. I'm unable to find any other articles for how to install libvirt that don't use homebrew or macports. 

> What package manager do you use on mac?

I don't use a package manager.

**Comment by mmlb** [comment]
> > Thanks for the extra context. I'm not seeing where libvirt _requires_ homebrew.
> 
> This [link](https://www.arthurkoziel.com/running-virt-manager-and-libvirt-on-macos/) shows the libvirt installation requiring homebrew. I'm unable to find any other articles for how to install libvirt that don't use homebrew or macports.

There's https://libvirt.org/compiling.html but I haven't tried it on mac so can't say anything about getting the dependencies. The recipes for libvirt for both macports and homebrew look pretty sane so it seems like the usual "ensure you have deps, mason configure, meson build, meson install" I guess.

> > What package manager do you use on mac?
> 
> I don't use a package manager.

I guess this issue/discussion has run its course though. No one seems to want libvirt on mac and you want virtualbox so there's no reason to drop virtualbox in favor of libvirt.
