### ISSUE TITLE
docker-compose quickstart breaks with ERROR: Invalid interpolation format for "tls-gen" option in service "services": "${FACILITY:-onprem}"

### ISSUE THREAD

**Issue by dch** [tinkerbell/sandbox#118]
## Expected Behaviour

```
$ docker-compose up -d
Creating network "compose_default" with the default driver
Creating volume "compose_postgres_data" with default driver
Creating volume "compose_certs" with default driver
Creating volume "compose_auth" with default driver
Pulling tls-gen (cfssl/cfssl:)...
latest: Pulling from cfssl/cfssl
* woot * ** party parrot **

```

## Current Behaviour

```
$ docker-compose up -d
ERROR: Invalid interpolation format for "tls-gen" option in service "services": "${FACILITY:-onprem}"
```

## Possible Solution

I think the precise version docker-compose needs to be specified. 2.x is already public, 1.26 is too old, and 1.29.2 works for me.

```
$ curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
```

## Steps to Reproduce (for bugs)

```
$ curl -L "https://github.com/docker/compose/releases/download/1.26/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
```

## Context

I was trying the simplest way to get to a running tinkerbell setup, assuming that docker-compose might be a good starting point.
 
## Your Environment

* Operating System and version (e.g. Linux, Windows, MacOS):

using an ubuntu 20.04.3 LTS VM.

* How are you running Tinkerbell? Using Vagrant & VirtualBox, Vagrant & Libvirt, on Packet using Terraform, or give details:

ubuntu vm

* Link to your project or a code example to reproduce issue:

n/a

**Comment by jacobweinstock** [comment]
Hey @dch, thanks for reporting this. Were you following this guide by chance? https://github.com/tinkerbell/sandbox/blob/main/docs/quickstarts/COMPOSE.md
It does mention a docker-compose version requirement, but maybe we need to present that in a different way.

**Comment by dch** [comment]
Yea a bit of this and perusing the vagrantfile from libvirt approach

**Comment by jacobweinstock** [comment]
Hey @dch. Based on your experience here, would you be willing to provide any feedback on what we could do to make the docker-compose version requirement more apparent?

**Comment by Akucina** [comment]
I had similar error prompt while running: docker-compose ps

Later, realized that I did not run: cd /vagrant/compose first.

/vargant is Synced Folder defined in Vagrant file: 

provisioner.vm.synced_folder '../', '/vagrant'
