### ISSUE TITLE
ERROR: for images-to-local-registry  Container ... is unhealthy

### ISSUE THREAD

**Issue by glycerin-ce** [tinkerbell/sandbox#119]
I', trying to set up a provisioner using the docker-compose container and actually I encounter an unhealthy status for 

ERROR: for images-to-local-registry  Container "356a4ca1b50a" is unhealthy.

ERROR: for osie-bootloader  Container "fa22bda087e8" exited with code 1.

## Steps to Reproduce (for bugs)

1. following your README for setting up a provisioner
2.
3.
4.

## Your Environment

* Operating System and version (e.g. Linux, Windows, MacOS):
* Linux Ubuntu Ubuntu 20.04.2 LTS

* How are you running Tinkerbell? Using Vagrant & VirtualBox, Vagrant & Libvirt, on Packet using Terraform, or give details:
* I'm trying using a proxmox's VM for the provisioner.

* Link to your project or a code example to reproduce issue:

**Comment by jacobweinstock** [comment]
Hey @glycerin-ce, thanks for trying out the sandbox! would you be able to share the output from that failed osie-bootloader container (`docker logs fa22bda087e8`)?

**Comment by glycerin-ce** [comment]
Thanks for your answer @jacobweinstock .
That container is not available.
Here you are the complete list:
# docker container ls
CONTAINER ID   IMAGE                                      COMMAND                  CREATED          STATUS                                  PORTS                                                                   NAMES
fc0439615ca5   quay.io/tinkerbell/tink-cli:sha-3743d31e   "/bin/sh -c 'sleep i…"   17 minutes ago   Up 17 minutes                                                                                                   compose_tink-cli_1
020913015ac5   quay.io/tinkerbell/hegel:sha-89cb9dc8      "/usr/bin/hegel"         17 minutes ago   Up 17 minutes                           0.0.0.0:50060-50061->50060-50061/tcp, :::50060-50061->50060-50061/tcp   compose_hegel_1
c91f9cd18c64   quay.io/tinkerbell/boots:sha-36f12f81      "/usr/bin/boots -dhc…"   17 minutes ago   Restarting (1) Less than a second ago                                                                           compose_boots_1
42fc811fc8d3   quay.io/tinkerbell/tink:sha-3743d31e       "/usr/bin/tink-server"   17 minutes ago   Up 17 minutes (healthy)                 0.0.0.0:42113-42114->42113-42114/tcp, :::42113-42114->42113-42114/tcp   compose_tink-server_1
d83f0d0bff9b   registry:2.7.1                             "/entrypoint.sh /etc…"   17 minutes ago   Restarting (1) 43 seconds ago                                                                                   compose_registry_1
ea1ef5efb02f   postgres:14-alpine                         "docker-entrypoint.s…"   17 minutes ago   Up 17 minutes (healthy)                 0.0.0.0:5432->5432/tcp, :::5432->5432/tcp                               compose_db_1
#

**Comment by glycerin-ce** [comment]
Hi @jacobweinstock 
Looking better I found a mistake into the .env configuration.
The TINKERBELL_HOST_IP value was wrong.
Now is running.
Thanks too much.

**Comment by jacobweinstock** [comment]
right on! glad to hear. thanks for asking!
