### ISSUE TITLE
Moving tls cert generation to terraform

### ISSUE THREAD

**Issue by wokalski** [tinkerbell/sandbox#135]
I've just moved tls cert generation to terraform in my local "fork". I find it much easier to understand than the generate.sh bash script. Would you accept such contribution?

**Comment by odacombe-bc** [comment]
I was thinking of doing the same, so yes I for one would like to see!

**Comment by jacobweinstock** [comment]
Thank you for bringing this up. For me, the challenge with this would be that we'd need to do something similar for vagrant and the bare docker-compose paths as well (if this is the model you are proposing). That's a lot more code, maintenance, and overhead.

If the goal is to improve understandability, maybe improving the code comments/documentation for the `generate.sh`would be an acceptable alternative? Very open to other ideas too.

**Comment by chrisdoherty4** [comment]
The code has since moved on and no longer performs cert generation. Dubbing this issue as stale.
