### ISSUE TITLE
Documentation for "On Bare Metal with Docker" setup is outdated

### ISSUE THREAD

**Issue by pjakuszew** [tinkerbell/sandbox#144]
I am trying to set up a test environment with Tinkerbell by going through this guide: https://docs.tinkerbell.org/setup/on-bare-metal-with-docker/

It is referring to `generate-env.sh` and `setup.sh` scripts, which do not exist either in main branch, or in v0.6.0 release.

Apparently these files were removed in commit 6b841fee7c52cef49f182b7835afc3c49e3a1321

**Comment by chrisdoherty4** [comment]
Stale issue.
