### ISSUE TITLE
Broken Documentation Links

### ISSUE THREAD

**Issue by saltyautomation** [tinkerbell/sandbox#149]
Documentation links for Creating Hardware Data, Templates, and Workflows are not working. 
## Expected Behaviour

When I click the link I should not get a 404
## Current Behaviour

When I click the links I get a 404
## Possible Solution

update the README.md
## Steps to Reproduce (for bugs)

1. From the main github page click and of the links in the get started section
2.
3.
4.

## Context

I had to go find the links on the tinkerbell page 

## Your Environment

Any web browser
* Operating System and version (e.g. Linux, Windows, MacOS):
All
* How are you running Tinkerbell? Using Vagrant & VirtualBox, Vagrant & Libvirt, on Packet using Terraform, or give details:
Docker
* Link to your project or a code example to reproduce issue:
I can submit a PR from my main branch if that is the proper next step.  https://github.com/saltyautomation/sandbox

**Comment by chrisdoherty4** [comment]
The documentation has moved on and no longer references these links.
