### ISSUE TITLE
Provisioner should be setup to NAT for the workers

### ISSUE THREAD

**Issue by mmlb** [tinkerbell/sandbox#31]
I'm not sure why we didn't do this from the beginning and I can't really think of a good reason to make the default setup not have internet access via the provisioner. If we enable routing and NAT'ing we'd be able to drop the local registry and the need to sync/re-tag images from the setup, and the workflows will be able to use the internet access to fetch from.

**Comment by mrmrcoleman** [comment]
Agree. I always run this:

`sudo iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
sudo iptables -A FORWARD -i eth1 -j ACCEPT
sudo iptables -A FORWARD -i eth0 -j ACCEPT`

Taken from this: https://kinvolk.io/blog/2020/10/provisioning-flatcar-container-linux-with-tinkerbell/

**Comment by gianarb** [comment]
We assumed it was made in this way with reasons, glad there are no good reasons for those extra steps.

**Comment by gianarb** [comment]
Anyway, great news. @Cbkhare can you have a look?

- [ ] Enable NAT for Terraform and Vagrant (you can check this running a workflow that uses https://hub.docker.com/_/hello-world directly from the Docker Hub.
- [ ] Update documentation removing what is not needed anymore

I think we are not ready to remove the registry yet. I want to speak about it during a contributor meeting. But this issue can be closed as soon as the NAT is in place 👍

**Comment by Cbkhare** [comment]
nat changes added via https://github.com/tinkerbell/tink/pull/410

**Comment by gianarb** [comment]
This has to be ported to this repository. The `setup.sh` scripts are independent

**Comment by Cbkhare** [comment]
@gianarb yes, I have discussed with @mmlb . I will raise a PR for this repo as well.

**Comment by Cbkhare** [comment]
PR for sandbox repo. https://github.com/tinkerbell/sandbox/pull/33

**Comment by Cbkhare** [comment]
PR for documentation https://github.com/tinkerbell/tinkerbell-docs/pull/55

**Comment by Cbkhare** [comment]
All Pr merged.

**Comment by gianarb** [comment]
Thanks @Cbkhare ! well done!
