### ISSUE TITLE
Remove internal registry

### ISSUE THREAD

**Issue by gianarb** [tinkerbell/sandbox#45]
We are not sure if the internal registry is something we want or if it is just a complication.

We enabled #41. So now the workers have access to the internet. It means that all the registry setup and the certificate to have it secure is not strictly required anymore.

BUT we will have to figure out by ourselves how to get our actions to run in the worker. This is not a problem when the action is public, but for private repositories, it is a bit more complicated and the operating system installation environment ([osie](https://github.com/tinkerbell/osie) or [tinkie](https://github.com/gianarb/tinkie)) will have to give us a way to inject authentication (or we have to make tink-worker good enough to authenticate I suppose)

**Comment by mmlb** [comment]
Yep private repo/images is something we should think about but I think the way to do it is to force it? I'm in favor of dropping the registry from sandbox.

**Comment by gianarb** [comment]
> I think the way to do it is to force it? 

What do you mean?

**Comment by mmlb** [comment]
Drop the registry so that we can have a discussion about this. Force the discussion.

**Comment by stolsma** [comment]
I agree with @mmlb, just drop it for now from the sandbox. It is easy to add again later and most people/orgs that need a private repo already have a policy and implementation or know how to set it up.... Just my 2 cents... :-)

**Comment by gianarb** [comment]
> need a private repo already have a policy and implementation or know how to set it up.... Just my 2 cents... :-)

Yeah, the problem is not how you set it up for yourself, but how you can use it in the installation environment if it has passwords or things like that. Anyway, I am always up for removing things 👍  I will leave time for more people to leave a comment, and at some point, I will move forward accordingly

**Comment by stolsma** [comment]
> Yeah, the problem is not how you set it up for yourself, but how you can use it in the installation environment if it has passwords or things like that

If you are running a private repo you always have that problem... :-( But this problem is also related to the encryption of the metadata path from provisioner to local executor. Thats something we need to make easy and save so all secrets can be transported in a save way.

**Comment by mrchrd** [comment]
I think I'd like to keep it for now for consistency with k8s-sandbox. @detiber how do you push freshly built dev images to k8s with tilt? Is the registry required/useful?

**Comment by fransvanberckel** [comment]
Beware i use a private repo registry for Docker images with the Ansible Playbook ...
https://github.com/fransvanberckel/ansible-role-tinkerbell

**Comment by gianarb** [comment]
@fransvanberckel can you tell me a bit more?! Do you rely on the private registry that sandbox provides or you just provision a registry as part of toolchain ansible-role-tinkerbell ships?

If it's the second no problem, you can keep shipping it. If it's the first removing it from the sandbox will require some work for the ansible role.

**Comment by fransvanberckel** [comment]
That's right, it's more the second. For more details, take a look at the role ...
https://github.com/fransvanberckel/ansible-role-tinkerbell/tree/master/roles/tinkerbell

**Comment by nicklasfrahm** [comment]
I think removing it is a good idea, because it simplifies things. If you seek to do private images or work in an airgapped environment, there are other ways to do it, like a private Docker registry with credentials or pre-pulling images.

**Comment by gianarb** [comment]
I have started to work at this and the problem is in OSIE (and tinkie @thebsdbox ).

OSIE: https://github.com/tinkerbell/osie/blob/master/apps/workflow-helper.sh#L81
Tinkie: https://github.com/gianarb/tinkie/blob/master/bootkit/main.go#L64

We use the internal registry as a way to select the version of tink-worker we want to run as part of the installation environment.

Currently, it works this way:

1. Sandbox has a file called `./current_versions.sh` it contains the publicly available tink-worker image
2. It gets moved to `.env` as part of the `./generate-envrc.sh` script
3. setup.sh pick it up and mirror it to the **private registry** always tagged as latest
4. In this way the various OSIEs implementation can pull and run it.

We can make it more general and we can write a new RULE to OSIE:

"OSIE use a expect a kernel command line called `tink-worker-image` or whatever and it uses its content to run the tink-worker. In this way, we can even override it via metadata"

if we all agree I can open PR against osie and tinkie and sandbox to have all of them inline

(At some point we should write OSIE RULES as documentation, but we don' know them all yet! :P )

**Comment by thebsdbox** [comment]
We can easily do this now, default to lates and override in the `facilities` metadata! 

```
    "facility": {
      "facility_code": "onprem tink-worker-tag=abc123",
```

How does that sound?

**Comment by nicklasfrahm** [comment]
@thebsdbox I am not too much into the details, but wouldn't it be better to create a new field in the facility object, because this could break applications, that use the facility code and build on top of the metadata.

**Comment by thebsdbox** [comment]
ah so this is an undocumented thing :| things in the facility code are passed to the cmdline. They're then presented as environment variables or in `/proc/cmdline` inside of OSIE and we can process them anyway we like. It won't break any existing functionality.

**Comment by gianarb** [comment]
Yep @thebsdbox I love that. Let's see what @mmlb says and I can proceed when we agree

**Comment by gianarb** [comment]
@nicklasfrahm yeah it is unfriendly and undocumented :) I think at some point we will figure out a better metadata structure for all of that. I think something is part of the this proposal @mmlb started but not totally sure https://github.com/tinkerbell/proposals/pull/25/files

**Comment by mmlb** [comment]
Yep I think this should be done in a metadata fashion but not like that @thebsdbox, boots already supports this in "cacher mode", we have "custom services version" that we use to boot different versions of osie (https://github.com/tinkerbell/boots/blob/master/packet/models_cacher.go#L319). Custom services is meant for this in the legacy EM stack and we should probably make use of that in tinkerbell too I think. I don't like the idea of injecting it through the `facility` param that is just layering bad UX on top of the bad stuff already :D.

I don't think this should be part of the Instance proposal @gianarb thats the wrong layer to do this I think.

The other option is to just pin it in the osie "package". Which is kind of the other side of doing things. I'm not too keen on this actually.

There are some runtime params that we should have a way to pass down to tink-worker. Its version seems like one, centralized logging config is another. I think maybe `hardware.metadata.services` is probably a better place? We can do something like:
```json
{
  "tink-worker": {
    "log-options": {
      "driver": "..."
    },
    "tag": "some-tag"
  }
}
```

**Comment by mmlb** [comment]
Hmm yeah we can go with option `2 cmdline`, maybe actually (`append_cmdline` ?). We already have the osie section in

```
network.interfaces[].netboot.osie | OSIE details
```
where we can add `append_cmdline`. https://docs.tinkerbell.org/hardware-data/

**Comment by gianarb** [comment]
I am confused, you say that cmdline where a bad idea right? :D

**Comment by mmlb** [comment]
The services proposal (workflow services actually) is not what I meant when I mentioned services... naming x)

**Comment by mmlb** [comment]
cmdline is definitely an option, but feels hacky (though its my favorite of the hacks). Having a proper way to get _some_ hardware data from tink-server (through hegel probably?) is I think the best option, but not as quick :D

**Comment by gianarb** [comment]
Ok, we (@mmlb) moved our conversation over prv Slack because here it was too hard and we find a common proposal! 

We are gonna teach Hegel a new endpoint `/worker` that will expose the content of `hardware.metadata.worker`. That field specifies how the worker that OSIE will start looks like.

The format is not yet defied but ideally something like:

```json
{
  "worker": {
    "log": {
      "driver": "..."
    },
    "image": "quay.io/tinkerbell/tink-worker:something",
    ....
  }
}
```
