### ISSUE TITLE
Move tink-cli from docker-compose to the actual host

### ISSUE THREAD

**Issue by gianarb** [tinkerbell/sandbox#49]
I think it is confusing and that great to use the CLI as a docker container. We have everything we need to move tink-cli out from docker-compose to the host itself. 

A brief description of how I think this issue can be resolved:

1. Remove the tink-cli service from docker-compose
2. Based on where we are (vagrant | terraform) we should install the tink-worker looking at the environment variable set here https://github.com/tinkerbell/sandbox/blob/master/current_versions.sh#L9 and we should do something like:

```terminal
docker pull $IMAGE
docker cp $IMAGE /tink /usr/local/bin/tink
```

2a. If we are on Vagrant use vagrant/tinkerbell.sh
2b. On terraform use the exec-remote provider
2c. DO NOT USE setup.sh because it is not its responsibility to install programs

3. Update doc, readme, and things like that

**Comment by stolsma** [comment]
What fo you think about publishing the tink cli architecture versions as artifacts on the tink github repo? You can then also use wget to download it wherever you want... Just like kubectl I think? (If I'm correct?)

**Comment by gianarb** [comment]
We have this problem because right now we do not tag the various projects
but only sandbox. We do it because right now the projects are not stable
enough for their own independent release cycle.

We built binaries only when tagging a new version from the sandbox
repository. GitHub has a limit in terms of how much space you can use and I
think it will become a limitation too quickly.

Having to retrieve the binary from the container is weird and unusual but
it is hidden by sandbox itself and kind of temporary solution. Who wants to
get the actual binary can download it from sandbox release page with wget
or everything else.

Sander Tolsma do you want to take this task? :)

**Comment by stolsma** [comment]
@gianarb I'l take a stab at it...😉 pull req will come tomorrow though, busy today. 😔

**Comment by gianarb** [comment]
Yay! Thanks no problem at all take your time!

**Comment by stolsma** [comment]
@tstromberg I'm just back from a long holiday,  will look into it tomorrow!

**Comment by stolsma** [comment]
@tstromberg Sorry, forgot to come back here too after closing #52 . 

The short answer is: nope, I'm not looking into this issue any more..

**Comment by chrisdoherty4** [comment]
Tink CLI is deprecated.
