### ISSUE TITLE
GitHub Self hosted runner uses go cache

### ISSUE THREAD

**Issue by gianarb** [tinkerbell/sandbox#58]
## Current Behaviour

We are not running vagrant tests because it gets cached from `go cache`

## Possible Solution

Set `GOFLAGS="-count=1"` in the `.env` action-runner file

## Environment

GitHub Action self hosted runner

/cc. @rawkode

**Comment by chrisdoherty4** [comment]
It doesn't look like we have self hosted runners any longer. If we encounter one and this is an issue we can reopen.
