### ISSUE TITLE
Centralise versions in a single place

### ISSUE THREAD

**Issue by gianarb** [tinkerbell/sandbox#6]
Right now versions for our components are everywhere:

* docker-compose
* generate-envrc

We need to create a file that will contain all of them, in this way it will e way easier to bump them up and check what a user is running. ideally, we will have to only ask: "can you copy paste the FILE_VERSION from sandbox?"

**Comment by gianarb** [comment]
I made some investigation that I have to validate yet.
[Docker Compose supports by default a `.env` file](https://docs.docker.com/compose/env-file/), if it exists all the docker-compose commands will read it.
This is a good place where we can place something like this:

```
export OSIE_DOWNLOAD_LINK=https://tinkerbell-oss.s3.amazonaws.com/osie-uploads/osie-v0-n=252,c=bc454bc,b=master.tar.gz
export TINKERBELL_TINK_SERVER_VERSION=quay.io/tinkerbell/tink:sha-adb49da
export TINKERBELL_TINK_CLI_VERSION=quay.io/tinkerbell/tink-cli:sha-adb49da
export TINKERBELL_TINK_BOOTS_VERSION=quay.io/tinkerbell/boots:327-58ab49913b5498908b16e2607d265a61a05f73b6
export TINKERBELL_TINK_HEGEL_VERSION=quay.io/tinkerbell/hegel:196-fa897aa020769db8becb9be29adaeb6be92a7fc7
export TINKERBELL_TINK_WORKER_VERSION=quay.io/tinkerbell/tink-worker:sha-adb49da
```
Now, we already have a envrc file, and my proposal is to move from envrc to .env. In this way the setup will look like:

```
./generate-envrc.sh eth0
source .env
./setup.sh
docker-compose up -d
```
If you need to change which version of tink-server gets loaded you can open the `.env` file and set the required docker image tag.

I like the idea to have a single `env` file for everything, we can keep the `envrc` but it will require a new flag when using docker-compose, and it makes that a bit less intuitive.

**Comment by thebsdbox** [comment]
This seems like an oversight in the first instance, the `.env` (not sure if it's a standard) however it is already a largely accepted method in various libraries to import variables into another running environment. So this sounds great to me.

**Comment by gianarb** [comment]
we did it!
