### ISSUE TITLE
Issue with published sandbox libvirt bootstrap image

### ISSUE THREAD

**Issue by detiber** [tinkerbell/sandbox#62]
## Expected Behaviour
Should be able to run vagrant up with the libvirt provisioner

## Current Behaviour
Provisioning with vagrant/libvirt fails

With the currently published bootstrap boxes, it appears that the libvirt box has a 0 byte file for `/usr/local/bin/docker-compose` instead of the expected docker-compose binary.

## Possible Solution
Publish an updated bootstrap image for libvirt that does not have a 0 byte file for `/usr/local/bin/docker-compose`

## Steps to Reproduce (for bugs)
1. On a Linux box with vagrant/libvirt, run vagrant up

## Your Environment
* Operating System and version (e.g. Linux, Windows, MacOS): Linux/Fedora 33

* How are you running Tinkerbell? Using Vagrant & Libvirt

**Comment by gianarb** [comment]
Thank you for reporting this issue. This is the script we use to build the baseimage https://github.com/tinkerbell/sandbox/tree/master/deploy/vagrant/basebox do you mind validating it please?

**Comment by detiber** [comment]
I tried building a box locally using the basebox configuration in tree, but ended up with a box that would not successfully ssh. I didn't troubleshoot any further, though.

**Comment by gianarb** [comment]
Solved by @mmlb and @nshalman #81 
https://app.vagrantup.com/tinkerbelloss/boxes/sandbox-ubuntu1804/versions/0.2.0

Thanks a lot
