### ISSUE TITLE
provisioner: ./setup.sh: line 117: NAT_INTERFACE: unbound variable

### ISSUE THREAD

**Issue by jlevensalor** [tinkerbell/sandbox#77]
## Expected Behaviour
Following steps on local setup with vagrant on Mac with Virtualbox installed.  Using this reference https://docs.tinkerbell.org/setup/local-vagrant/
Docs say to look for line INFO: tinkerbell stack setup completed successfully on ubuntu server
After running the command vagrant up provisioner 

## Current Behaviour
Instead I get to the ./setup.sh output and 
 provisioner: + ./setup.sh
    provisioner: INFO: starting tinkerbell stack setup
    provisioner: INFO: verifying prerequisites for ubuntu (18.04)
    provisioner:        Found prerequisite: docker
    provisioner:        Found prerequisite: docker-compose
    provisioner:        Found prerequisite: ip
    provisioner:        Found prerequisite: jq
    provisioner:        Found prerequisite: netplan
    provisioner: INFO: waiting for the network configuration to be applied by systemd-networkd
    provisioner: INFO: tinkerbell network interface configured successfully
    provisioner: ./setup.sh: line 117: NAT_INTERFACE: unbound variable
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

## Possible Solution
I noticed the setup.sh file was modified yesterday on April 8'21 but have not done deep dive on diffs just yet.  

## Steps to Reproduce (for bugs)
1. git clone https://github.com/tinkerbell/sandbox.git
2. cd sandbox/deploy/vagrant
3. vagrant up provisioner 

## Context
Just opening issue if it might be an easy fix for diff summary on code commits. 
One note - if I ignore the error and just vagrant ssh provisioner, I do get dropped in to the a prompt in the provisioner so may just be background error.  Will continue with steps to setup and see if it prevents any progress.  

## Your Environment

* Operating System and version (e.g. Linux, Windows, MacOS):
Mac OS Big sur 11.2.3 
VirtualBox Graphical User Interface
Version 6.1.18 r142142 (Qt5.6.3

* Link to your project or a code example to reproduce issue:

**Comment by nshalman** [comment]
This was my fault. Thanks for reporting!! Should be fixed by #78.

**Comment by jlevensalor** [comment]
Agreed, git pull, re-run and issue is no longer there for setup.sh, glad I was able to help out.  Moving on to more testing in the homelab.  Cheers!
