### ISSUE TITLE
Create a GitHub Action workflow that validate Terraform Setup guide

### ISSUE THREAD

**Issue by gianarb** [tinkerbell/sandbox#8]
Create a similar [test suite](https://github.com/tinkerbell/sandbox/blob/master/test/_vagrant/vagrant_test.go) as the one we use to validate Vagrant but for Terraform on Equinix Metal

**Comment by gianarb** [comment]
We can't do until #1 is over

**Comment by invidian** [comment]
#1 is now done, so this can be closed too? I see https://github.com/tinkerbell/sandbox/runs/1662739685?check_suite_focus=true being run.

**Comment by gianarb** [comment]
This issue to be closed requires a GitHub Action pipeline that validate that the Terrafrom Setup guide works. It is not done yet :( let me change the title

**Comment by invidian** [comment]
Ah, my bad. We only have a Vagrant check. Sorry for the noise :)
