### ISSUE TITLE
e2e validation for vagrant images with Goss

### ISSUE THREAD

**Issue by gianarb** [tinkerbell/sandbox#82]
Goss is a popular framework that helps you to test docker images and servers
https://github.com/aelsabbahy/goss

We can do basic but important checks like:
* Docker in installed and running
* Docker-Compose --help runs and returns what we expect
* ...

Ideally, we can run it as part of the `provisioning.sh` script

**Comment by chrisdoherty4** [comment]
Having had no interest for quite some time this issue is being considered stale.
