### ISSUE TITLE
Vagrant box version appears not to exist

### ISSUE THREAD

**Issue by jimmyat** [tinkerbell/sandbox#84]
## Expected Behaviour
Running `vagrant up provisioner` should spin up the provisioner vagrant box as usual.

## Current Behaviour
An error indicating the box does not exist appears:

```
The box you're attempting to add has no available version that
matches the constraints you requested. Please double-check your
settings. Also verify that if you specified version constraints,
that the provider you wish to use is available for these constraints.

Box: tinkerbelloss/sandbox-ubuntu1804
Address: https://vagrantcloud.com/tinkerbelloss/sandbox-ubuntu1804
Constraints: 0.2.0
Available versions: 0.1.0
```

However, version 0.2.0 appears to be present at https://vagrantcloud.com/tinkerbelloss/sandbox-ubuntu1804

## Steps to Reproduce (for bugs)
1. Clone the sandbox repo.
2. Run `cd sandbox/deploy/vagrant && vagrant up provisioner`

Output:

```
~/sandbox/deploy/vagrant# vagrant up provisioner
Bringing machine 'provisioner' up with 'virtualbox' provider...
==> provisioner: Box 'tinkerbelloss/sandbox-ubuntu1804' could not be found. Attempting to find and install...
    provisioner: Box Provider: virtualbox
    provisioner: Box Version: 0.2.0
==> provisioner: Loading metadata for box 'tinkerbelloss/sandbox-ubuntu1804'
    provisioner: URL: https://vagrantcloud.com/tinkerbelloss/sandbox-ubuntu1804
The box you're attempting to add has no available version that
matches the constraints you requested. Please double-check your
settings. Also verify that if you specified version constraints,
that the provider you wish to use is available for these constraints.

Box: tinkerbelloss/sandbox-ubuntu1804
Address: https://vagrantcloud.com/tinkerbelloss/sandbox-ubuntu1804
Constraints: 0.2.0
Available versions: 0.1.0
```

## Context
Tested on MacOS and Debian with freshly cloned copies of the `sandbox` repo. This prevents use of `sandbox` on vagrant entirely.

## Your Environment
tested on Debian Buster & MacOS Big Sur, using the vagrant provider for sandbox.

**Comment by gianarb** [comment]
Hello @jimmyat ! Thank you for reporting this issue, I fixed it!
Apparently, there is an extra step I didn't figure out! The image was uploaded but not actually released!

![Screenshot 2021-05-04 at 16 10 57](https://user-images.githubusercontent.com/1630267/117016878-6d8e3a00-acf3-11eb-9581-70b2ad03415a.png)

**Comment by jimmyat** [comment]
thanks @gianarb!
