### ISSUE TITLE
mount.nfs requested NFS version or transport protocol is not supported

### ISSUE THREAD

**Issue by MikePadge** [tinkerbell/sandbox#97]
Debian10
Vagrant 2.2.18
Most recent sandbox

## Expected Behaviour

cd sandbox/deploy/vagrant `vagrant up provisioner` - starts the sandbox 

## Current Behaviour

```
==> provisioner: Mounting NFS shared folders...
==> provisioner: Pruning invalid NFS exports. Administrator privileges will be required...
==> provisioner: Removing domain...
==> provisioner: Deleting the machine folder
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o vers=4,rw,vers=4,tcp 192.168.121.1:/home/banner/Documents/Lib/Tinkerbell/deploy /vagrant

Stdout from the command:

Stderr from the command:

mount.nfs: requested NFS version or transport protocol is not supported
```

## Steps to Reproduce (for bugs)

1. Install debian10
2. install vagrant
3. install kvm-libvirt
4. run vagrant up

## Your Environment

* Operating System and version (e.g. Linux, Windows, MacOS):

* How are you running Tinkerbell? Using Vagrant & VirtualBox, Vagrant & Libvirt, on Packet using Terraform, or give details:
Vagrant + Libvirt 

I tried this on two separate servers, both debian10. Both incurred the same error. 
```
vagrant plugin list
vagrant-docker-compose (1.5.1, global)
vagrant-libvirt (0.5.3, global)
```

It's late, I could have very easily overlooked something dumb, but I haven't gone out of my way to do crazy things here. Just pulled the repo and run vagrant up.

**Comment by MikePadge** [comment]
> Hey @MikePadge, thanks for reporting this. I've opened PR #98 that should fix this.

Welp, I feel dumb, but that did the trick. Thank you kindly.

**Comment by MikePadge** [comment]
Actually @jacobweinstock this completely breaks the docker-compose setups inside the vagrant containers, probably something to do with the extreme finicky of docker and nfs. 

I can get away with nfsd, I was just looking in the wrong place, thinking I needed a vagrant nfs plugin or something I couldn't find.

**Comment by jacobweinstock** [comment]
Hey @MikePadge, sorry I'm not following. The PR #98 breaks the docker-compose? That PR doesn't use NFS anymore.
