### ISSUE TITLE
Ansible as first-class means of sandbox deployment

### ISSUE THREAD

**Issue by jmpolom** [tinkerbell/sandbox#99]
## Expected Behaviour
Well, I'm not sure if I really have any expectations beyond what is already provided.

## Current Behaviour
Sandbox ships a number of deployment methods but an ansible playbook/role is not one of them. Particularly, docker-compose is a method that's attractive for small scale "dip your toes in" deployments but is not super friendly to those of us who plan to use `podman` instead of docker.

## Possible Solution
Develop an ansible role that deploys the sandbox using either docker or podman. Along the lines of what is done with [ceph-ansible](https://github.com/ceph/ceph-ansible).

## Steps to Reproduce (for bugs)

1. Evaluate sandbox repo.
2. Draw conclusions from observation.

## Context
We're attempting to use tinkerbell but we're not very interested in using docker. We've developed quite a liking for podman though and seeing as they can pretty much run the same containers, plan to develop a method for getting the sandbox up with podman. Recent versions of podman do support docker-compose via the podman unix socket but compose is a pretty fragile format it seems. Different versions of docker-compose support different directives in the yaml format (ex: `service_completed_successfully` was removed and later added back to docker-compose) and support varies a bit across podman versions. The use of docker-compose also implicitly suggests deployment is favored towards docker as opposed to other container runtimes like podman. Ansible would allow development of a more runtime neutral deployment method.

## Your Environment

* Operating System and version (e.g. Linux, Windows, MacOS): Fedora 34 and Debian testing

* How are you running Tinkerbell? Using Vagrant & VirtualBox, Vagrant & Libvirt, on Packet using Terraform, or give details: rootless podman containers

* Link to your project or a code example to reproduce issue:

**Comment by jacobweinstock** [comment]
Hey @jmpolom, this seems very doable. For the docker-compose to podman hopefully should only require some minor modifications to the existing docker-compose.yml file. If you've got anything started please do submit a regular or draft PR or a repo branch and we can collaborate.

**Comment by jmpolom** [comment]
Thanks for the response. I think we're going to start working on this and we'll definitely send over a PR when we have something we feel is worth your time.

**Comment by jacobweinstock** [comment]
Hey @djpbessems, any chance there are any docs to help me understand how to use this? my Ansible is quite rusty and I'm having some difficulty finding where the code is for deploying the sandbox.

**Comment by dch** [comment]
ditto here. I'm interested in a non-docker solution too, & familiar with ansible.

**Comment by alancaldelas** [comment]
Any updates with this?
